language: objective-c

before_install:
  #- gem install cocoapods
  - rvm 1.9.3

xcode_workspace: CijeneGoriva.xcworkspace
xcode_scheme: CijeneGoriva
xcode_configuration: Debug 
xcode_arch: i386 
xcode_sdk: iphonesimulator
xctool_args: -freshSimulator -freshInstall
