language: objective-c

before_install:
  - gem install cocoapods
  - rvm 1.9.3

script:
  xctool -workspace CijeneGoriva.xcworkspace -scheme CijeneGoriva -sdk iphonesimulator build test -freshInstall -freshSimulator
