language: objective-c

#xcode_sdk: iphonesimulator
#env: XCODEBUILD_SETTINGS="-sdk iphonesimulator" #XCCONFIGURATION=Debug 

before_install: 
  - cat ~/.rvmrc
  - rvm 2.0.0
  - rvm use ruby-2.0.0-p247

xcode_workspace: CijeneGoriva.xcworkspace
xcode_scheme: CijeneGoriva
xcode_configuration: Debug 
xcode_arch: i386 
xcode_sdk: iphonesimulator7.0
